### ISSUE TITLE
When ECPay sends a complete request to a order that has been completed, we should not get "on hold" status.

### ISSUE THREAD

**Issue by xqiu** [ECPay/Magento_PHP#2]
I caught in a situation, that the order has been marked as complete (from pending payment) (through Union Pay), but somehow ECPay send another same request, causing my order to be on hold.  So I have to change the following line in order to prevent such issue.  Please change the code to if the order is completed, and if the ECPay send another request as completed, we should stay complete status instead of on hold.

Magento_PHP/ECPay_Payment_Magento/app/code/local/ECPay/Foundation/ECPay_ProcessingController.php
Line 208
            } else {
                $oOrder->setState(Mage_Sales_Model_Order::STATE_HOLDED, TRUE, '失敗');
                $oOrder->save();
            }

**Comment by AllennChang** [comment]
Thank you, I will respond to the development team.

**Comment by AllennChang** [comment]
Can you send your order number to techsupport@greenworld.com.tw?  (somehow ECPay sends another same request), thank you.
