### ISSUE TITLE
code/local/ECPay/EcpayPayment directory case is not matching with etc/modules

### ISSUE THREAD

**Issue by zelik888** [ECPay/Magento_PHP#4]
Directory name is ECPay but in module references use Ecpay.. Causes errors on Ubuntu

**Comment by gogobu** [comment]
encountered the same issue here. please fix it.

**Comment by adityaputra** [comment]
It's been six months and.....
Anyone have a complete fix / workaround? I am trying to fix the issue but there always be another issue coming up after another. Seems to be "just" a file and variable naming problem but it is a big issue. It's like affecting everything.

**Comment by AllennChang** [comment]
感謝你們的反應，我會回饋給開發團隊進行評估，感謝

**Comment by AllennChang** [comment]
Hello, Please contact our technical customer service team and we will arrange a commissioner to assist you with your questions. Please send an email to techsupport@ecpay.com.tw.
