### ISSUE TITLE
有開發magento2.x 版本的嗎

### ISSUE THREAD

**Issue by benyang2015** [ECPay/Magento_PHP#5]

**Comment by AllennChang** [comment]
您好,抱歉, 目前尚未支援magento2.x的版本, 感謝您的發問,

**Comment by AllennChang** [comment]
@benyang2015  您好, 我們已安排計劃開發 magento2.x的版本,

**Comment by AllennChang** [comment]
請參考 https://github.com/ECPay/Magento2.3.3
