### ISSUE TITLE
Magento 1 end of life

### ISSUE THREAD

**Issue by borde91** [ECPay/Magento_PHP#6]
As magento 1 is quite an outdated technology and also close to its end of life, do you have any plans on a magento 2.x extension release? If so, do you have an ETA?

**Comment by adityaputra** [comment]
@borde91 I think they had it somewhere long time ago (can't be 100% sure about this) but I can't find it in their repo anymore. If you really need the ecpay extension, I think it's fairly simple process. They have good enough documentation of their API in English and pretty responsive support team. Actually someone at my company built the M2 extension for Ecpay without any major difficulty.

**Comment by AllennChang** [comment]
@borde91  Yes, We have planned to develop Magento2.x extension, but the release time is not determined

**Comment by borde91** [comment]
Thanks everybody for the reply. I'm hiring a developer to develop the magento 2 module, I just have a question (and I apology if this is not the correct place where to post such question) I hope you can help me clarify. Reading the official documentation it seems like the customer has to leave my store and land in the ecpay website in order to use the "barcode" payment. Is that really necessary? Or is it possible to have the user never leave my site while using such payment mode?

**Comment by AllennChang** [comment]
@borde91  Hi, please mail your question to techsupport@ecpay.com.tw . We will have a professional team to respond to your question.
